title: ManyMusic-Rec
description: Progress documentation for ManyMusic-EXG recording
version: 0.1.0
baseurl: manymusic.net
language: en
theme: just-the-docs
url: https://manymusic.net/rec/
aux_links:
  project-home: https://manymusic.net/
ga_tracking: "G-CPHVGWTS9L"
ga_tracking_anonymize_ip: true